version: 1

update_configs:
- package_manager: "dotnet:nuget"
  directory: "/Controls/BootstrapColorpicker/"
  update_schedule: "live"
  allowed_updates:
    - match:
        dependency_name: "DotVVM*"
